name: Build ZMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@9f3a8b2c7e
    with:
      build_matrix: |
        [
          {
            "board": "nice_nano_v2",
            "shield": "breeze_left"
          },
          {
            "board": "nice_nano_v2",
            "shield": "breeze_right"
          }
        ]
